### ISSUE TITLE
Kubeadm - When reset issued still tries to load a POD

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#154] opened 2017-05-24 16:19 UTC
Is this normal behavior. Under kubernetes without hyperd, I noticed that there is no attempt to spin up DNS pods. However, when I issue a kubeadm reset to start over there is an attempt by hyperd to start a kube-dns pod:

hyperd[1009]: E0524 10:19:59.988202    1009 persist.go:113] Pod[k8s_POD.0_kube-dns-3913472980-2jz1j_kube-system_af1d4552-3f1e-11e7-aeb4-0021ccd48ab5_10cd9672] failed to load sandbox info: leveldb: not found

Have not noticed this behavior under a non-hyperd kubernetes cluster.

Perhaps this is just a remnant but I did perform a kubeadm reset and then decided to reboot before peforming a new kubeadm init. In checking the status of hyperd after the reboot (prior to peforming a new kubeadm init) the above was the result.

Also when a kubeadm reset is done, all files in /etc/cni/net.d are removed. This should be noted in the deploy.md just as a warning or note

Thanks
DB

**Comment by resouer** [comment] 2017-05-25 02:57
@DarkBlaez The log above is normal which is caused by hyperd restart, don't worry.

> Also when a kubeadm reset is done, all files in /etc/cni/net.d are removed. This should be noted in the deploy.md just as a warning or note

Definitely, would you like to send a PR for this? It would be awesome to have you as frakti's  contributor.

**Comment by DarkBlaez** [comment] 2017-05-25 14:27
Sure sounds great and will issue PR and contribute

Thanks
DB

**Comment by DarkBlaez** [comment] 2017-06-05 18:51
The bigger issue over having to recreate the cni files is more around hyperd per above...

hyperd[1009]: E0524 10:19:59.988202 1009 persist.go:113] Pod[k8s_POD.0_kube-dns-3913472980-2jz1j_kube-system_af1d4552-3f1e-11e7-aeb4-0021ccd48ab5_10cd9672] failed to load sandbox info: leveldb: not found

Not sure why hyperd is trying to load this since a kubeadm reset was issued. This causes a number of problems if re-initializing a kubernetes cluster. The steps to resolve are unclear and thus makes using hyperd/frakti at this stage not viable.

DB

**Comment by feiskyer** [comment] 2017-06-26 02:31
The problem should be fixed now. Closing this one. 

@DarkBlaez Feel free to reopen it if you still encounter problems.

**Closed by feiskyer** 2017-06-26 02:31 UTC
